basePath: /gwt/api/v1
definitions:
  api.BaseRespBody:
    properties:
      code:
        description: 返回码
        type: integer
      data:
        description: 数据
        type: object
      message:
        description: 返回信息
        type: string
    type: object
  api.GetUserRespAPI:
    properties:
      code:
        description: 返回码
        type: integer
      data:
        $ref: '#/definitions/val.GetUserResp'
        description: 内容
        type: object
      message:
        description: 返回信息
        type: string
    type: object
  api.GetUsersRespAPI:
    properties:
      code:
        description: 返回码
        type: integer
      data:
        description: 内容
        items:
          $ref: '#/definitions/val.GetUserResp'
        type: array
      message:
        description: 返回信息
        type: string
    type: object
  api.GetUsersWithPageAPI:
    properties:
      code:
        description: 返回码
        type: integer
      content:
        $ref: '#/definitions/api.UsersPageModelAPI'
        description: 内容
        type: object
      message:
        description: 返回信息
        type: string
    type: object
  api.UsersPageModelAPI:
    properties:
      page_num:
        description: 页码
        type: integer
      page_size:
        description: 每页大小
        type: integer
      records:
        description: 数据
        items:
          $ref: '#/definitions/val.GetUserResp'
        type: array
      total_pages:
        description: 总页数
        type: integer
      total_records:
        description: 总记录条数
        type: integer
    type: object
  val.AddUserReq:
    properties:
      age:
        description: 年龄
        type: integer
      nickname:
        description: 昵称
        type: string
      username:
        description: 用户名
        type: string
    required:
    - age
    - username
    type: object
  val.DeleteUserReq:
    properties:
      id:
        description: 用户id
        type: integer
    required:
    - id
    type: object
  val.GetUserResp:
    properties:
      age:
        description: 年龄
        type: integer
      id:
        description: 用户id
        type: integer
      nickname:
        description: 昵称
        type: string
      username:
        description: 用户名
        type: string
    type: object
  val.UpdateUserReq:
    properties:
      age:
        description: 年龄
        type: integer
      id:
        description: 用户id
        type: integer
      nickname:
        description: 昵称
        type: string
      username:
        description: 用户名
        type: string
    required:
    - id
    type: object
host: localhost:8080
info:
  contact: {}
  license: {}
  title: golang-web-template 接口文档
  version: "1.0"
paths:
  /user:
    delete:
      consumes:
      - application/json
      description: 删除用户
      parameters:
      - description: 用户
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/val.DeleteUserReq'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.BaseRespBody'
      summary: 删除用户
      tags:
      - User
    post:
      consumes:
      - application/json
      description: 新增用户
      parameters:
      - description: 用户
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/val.AddUserReq'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.BaseRespBody'
      summary: 新增用户
      tags:
      - User
    put:
      consumes:
      - application/json
      description: 修改用户
      parameters:
      - description: 用户
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/val.UpdateUserReq'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.BaseRespBody'
      summary: 修改用户
      tags:
      - User
  /user/{id}:
    get:
      description: 查询用户 单个
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.GetUserRespAPI'
      summary: 查询用户 单个
      tags:
      - User
  /users:
    get:
      description: 查询用户 列表
      parameters:
      - description: 用户名
        in: query
        name: username
        type: string
      - description: 昵称
        in: query
        name: nickname
        type: string
      - description: 年龄
        in: query
        name: age
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.GetUsersRespAPI'
      summary: 查询用户 列表
      tags:
      - User
  /users/page:
    get:
      description: 查询用户 分页
      parameters:
      - description: 页码
        in: query
        name: page_num
        required: true
        type: string
      - description: 每页大小
        in: query
        name: page_size
        required: true
        type: string
      - description: 用户名
        in: query
        name: username
        type: string
      - description: 昵称
        in: query
        name: nickname
        type: string
      - description: 年龄
        in: query
        name: age
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.GetUsersWithPageAPI'
      summary: 查询用户 分页
      tags:
      - User
swagger: "2.0"
